language: c
os: linux
group: edge
addons:
  apt:
    packages:
    - libjansson-dev
    - libxml2-dev
    - libsqlite3-dev
    - libical-dev
    - libsasl2-dev
    - libssl-dev
    - libopendkim-dev
    - libcunit1-dev
    - libpcre3-dev
    - uuid-dev
    - libdb-dev
    - libbsd-dev
    - libmilter-dev
    - graphviz
    - doxygen
    - help2man
    - python-docutils
    - python-pygments
    - libmagic-dev
env:
  global:
  - CYRUSLIBS="/usr/local/cyruslibs"
  - PKG_CONFIG_PATH="$CYRUSLIBS/lib/pkgconfig:$PKG_CONFIG_PATH"
  - LDFLAGS="-Wl,-rpath,$CYRUSLIBS/lib -Wl,-rpath,$CYRUSLIBS/lib/x86_64-linux-gnu"
  - XAPIAN_CONFIG="$CYRUSLIBS/bin/xapian-config-1.5"
  - PATH="$CYRUSLIBS/bin:$PATH"
  - USE_CCACHE=1
cache:
  apt: true
  ccache: true
os: linux
compiler: gcc
install:
- git clone -b cyrus --single-branch https://github.com/cyrusimap/xapian.git xapian
- pushd xapian
- "./bootstrap"
- "./configure --enable-silent-rules --prefix=$CYRUSLIBS"
- pushd xapian-core
- make -j 8
- sudo make install
- popd
- popd
before_script:
- ccache --version
- ccache --zero-stats
- autoreconf -i -s
- ./configure CFLAGS="-W -Wno-unused-parameter -g -O0 -Wall -Wextra -Werror -fPIC"
  --enable-coverage --enable-calalarmd --enable-autocreate --enable-nntp --enable-http
  --enable-xapian --enable-unit-tests --enable-replication --with-openssl=yes
  --enable-murder --enable-idled --enable-sieve
- make -k
script:
- make check
branches:
  only:
  - master
  - cyrus-imapd-3.2
  - cyrus-imapd-3.0
notifications:
  slack:
      secure: Hr1H/7wbYq9HXnV9pW6sDrbafIwgAVx2Uk5sIHZL2rCt9Wl2rbSB7I/PA6ds4JSha9W23GV4MngSuFPEvL0sJ7MPyEGY+Ts0MnaYfChATNqFMM16lzbf7HvwXe81ubhJ/j4ZFcaXiVO+6qTvrKx8Ml9aVPENXld9ScqVgFo1h9UA059HikrdMbyO2lvBBCXcXZyv9XFK3AODGCvPEAKkmaD7Wa0G6lht9rhrHNxcTdZfAjE9M2WCmK1XimoHYUwgQqK7zXKamX7RU9QyhG4p7t/TFXJJz+Qh1T/iKd2hRpuTl6U8YVGSPLmsUSTKCUcDzXavN92ImEqnx3dWEXRl9g8bpZGoDyx/bi55WBQVeF54iCr+zwnRj8k71tZyYYkj/6xK/mvM+TMgEkw4mPdXJUJxoMuQVEZU0f0q1fqDaPFGVg3wEq1ES3gCadeehvib/7tHE0YmWeuhUCdBfuF1G+OUN/Ce4Q5NvvcsHUHhBqMEJpglPLJLElcxD9WNK1XdNCVwFl3PvPkLXcCBoshQ3TWB/vatkKy7N+8ADbzNJA8/djNcijtk8c7dNfNO3RKTixRwe/WgLcVsFe6kkLg5HnQw3uAk204F8mzJU1bgtknoIpgcHdVR608I/4cOnPNZWBQAGEHdle/EzWK/MF4mzPbHNaS8qfPtd2lyFgBJyOI=
