language: c
sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - libxml2-dev
    - libsqlite3-dev
    - libical-dev
    - libsasl2-dev
    - libssl-dev
    - libopendkim-dev
    - libcunit1-dev
    - libpcre3-dev
    - uuid-dev
    - libdb-dev
    - libbsd-dev
    - libmilter-dev
    - graphviz
    - doxygen
    - help2man
    - python-docutils
    - libmagic-dev
env:
  global:
  - CYRUSLIBS="/usr/local/cyruslibs"
  - PKG_CONFIG_PATH="$CYRUSLIBS/lib/pkgconfig:$PKG_CONFIG_PATH"
  - LDFLAGS="-Wl,-rpath,$CYRUSLIBS/lib -Wl,-rpath,$CYRUSLIBS/lib/x86_64-linux-gnu"
  - XAPIAN_CONFIG="$CYRUSLIBS/bin/xapian-config-1.5"
  - PATH="$CYRUSLIBS/bin:$PATH"
  - USE_CCACHE=1
cache:
  apt: true
  ccache: true
os: linux
compiler: gcc
install:
# libjanson
- git clone -b cyrus --single-branch https://github.com/cyrusimap/jansson.git janson
- pushd janson
- "autoreconf -v -i"
- "./configure --enable-silent-rules --prefix=CYRUSLIBS"
- make -j 8
- sudo make install
- popd #janson
  # Xapian
- git clone -b cyrus --single-branch https://github.com/cyrusimap/xapian.git xapian
- pushd xapian
- "./bootstrap"
- "./configure --enable-silent-rules --prefix=$CYRUSLIBS"
- pushd xapian-core
- make -j 8
- sudo make install
- popd #xapian-core
- popd #xapian
before_script:
- ccache --version
- ccache --zero-stats
- autoreconf -i -s
- ./configure CFLAGS="-W -Wno-unused-parameter -g -O0 -Wall -Wextra -Werror -fPIC"
  --enable-coverage --enable-calalarmd --enable-autocreate --enable-nntp --enable-http
  --enable-jmap --enable-xapian --enable-unit-tests --enable-replication --with-openssl=yes
  --enable-murder --enable-idled --enable-sieve
- make
script:
- make check
branches:
  only:
  - master
  - cyrus-imapd-3.0
notifications:
  slack:
    on_pull_requests: false
    on_success: change
    on_failure: always
    secure:
      bh4PiwcHYwn2qjKgidSKX6Ibq/Gt8+q6IL7YDWlfpDPYCuzdzSHBpm8qMpmBIjTemnsragJeR4pO9XEX20nhE9Lr7915wiBmYWqcmvcJGpJ1/nJz2lJYtBKl/dKZguQn3g4A+JgjUuXgzllI4ZsbbRkzL8dBC+py34p4ANtMKycXeGCwysnPfHav5VxQQnOsJUbIKDJiJPON2cR7e8quE6WpS1mEzUD+kaRWMUImKktMX1hrQH/71tNNMTqv0eHewci1akaZecFtXQi8D9Yfh1YBm8yxdLI9EgnglonEgbBCGG6WRODcxu/gEJlvXFMN+c4ojoyq4lNGnEqzLjDDVI1LoCNUcWbMFFhIGAA1SE+71fwDlKjLxUzodgJPb/yrWy4uwx8eBM3W8PIhFgZyo0irlV/0U3zNFWjjNPTRXUNNIZQu2XDLAhpiRZbMn4zsvydq2ngWnTdJfgpycYiBfL5zNdwdPpAQomQLl1JakWqyMSBZtz3Hbv3vRmb4rIogh5AHuwxKQrK5JNI9eZ5yPI7eUEpTq1nYD7syZPDj3gddjdteBx8ShjHH6ddteQX2OSUXwtiF90cEgYq0z8j2HxaNRIVrkeUNyeRTZXZ0wxWM7Fcz0Z7fRzsv1CXZwjDPmxARiIhbVhXxTgbED9+i2aCH9aZNrMTqoRUQWjLzgXw=
